In [7]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer


from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

# Load data
df = pd.read_csv('/content/namescodeA.csv')

# Input & Output
X = df["Name"]
Y = df["Country_code"].values
print(Y)


['ar_AE' 'ar_AE' 'ar_AE' 'ar_AE' 'ar_AE' 'ar_AE' 'ar_AE' 'ar_AE' 'ar_AE'
 'ar_EG' 'ar_EG' 'ar_EG' 'ar_EG' 'ar_EG' 'ar_EG' 'ar_EG' 'ar_EG' 'ar_EG'
 'ar_EG' 'ar_JO' 'ar_JO' 'ar_JO' 'ar_JO' 'ar_JO' 'ar_JO' 'ar_JO' 'ar_JO'
 'ar_JO' 'ar_JO' 'ar_PS' 'ar_PS' 'ar_PS' 'ar_PS' 'ar_PS' 'ar_PS' 'ar_PS'
 'ar_PS' 'ar_PS' 'ar_PS' 'ar_SA' 'ar_SA' 'ar_SA' 'ar_SA' 'ar_SA' 'ar_SA'
 'ar_SA' 'ar_SA' 'ar_SA' 'ar_SA' 'az_AZ' 'az_AZ' 'az_AZ' 'az_AZ' 'az_AZ'
 'az_AZ' 'az_AZ' 'az_AZ' 'az_AZ' 'az_AZ']


In [8]:

# Encode labels
label_encoder = LabelEncoder()
Y = label_encoder.fit_transform(Y)
# print(Y)
# print(np.unique(Y))
Y = to_categorical(Y)

# Text → TF-IDF
token = Tokenizer()
token.fit_on_texts(X)
X = token.texts_to_matrix(X, mode="tfidf")

# Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

# Model
model = Sequential([
    Dense(8, activation='relu', input_shape=(X.shape[1],)),
    Dense(64, activation='relu'),
    Dense(Y.shape[1], activation='softmax')
])

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, Y_train, epochs=60)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/60
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - accuracy: 0.1702 - loss: 1.8317
Epoch 2/60
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.1915 - loss: 1.8167
Epoch 3/60
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.1915 - loss: 1.8037
Epoch 4/60
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.2340 - loss: 1.7918
Epoch 5/60
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.2340 - loss: 1.7811
Epoch 6/60
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.2340 - loss: 1.7700
Epoch 7/60
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.2128 - loss: 1.7595
Epoch 8/60
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.2128 - loss: 1.7498
Epoch 9/60
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.2340 - loss: 1.7400
Epoch 10/60
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.2340 - loss: 1.7303
Epoch 11/60
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.2340 - loss: 1.7212
Epoch 12/60
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.2553 - loss: 1.7112
E

In [10]:
loss, accuracy = model.evaluate(X_test, Y_test)
print("Test Accuracy:", accuracy)

# Confusion Matrix
pred = model.predict(X_test)
Y_pred = np.argmax(pred, axis=1)
Y_true = np.argmax(Y_test, axis=1)

print(confusion_matrix(Y_true, Y_pred))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.0833 - loss: 2.1517
Test Accuracy: 0.0833333358168602
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
[[0 0 0 1 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 1 2]
 [1 0 0 0 0 1]
 [0 0 0 0 1 3]
 [0 0 0 0 0 0]]


In [29]:
# Example Prediction - Not Required
sample_name = ["Fahmy Al Kharafi"]

sample_vector = token.texts_to_matrix(sample_name, mode="tfidf")

prediction = model.predict(sample_vector)

predicted_class = np.argmax(prediction)

predicted_label = label_encoder.inverse_transform([predicted_class])

print("\nPredicted Country Code:", predicted_label[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step

Predicted Country Code: ar_SA
